candidates_index:
    path:     /
    defaults: { _controller: "AppBundle:Candidates:index" }
    methods:  GET

candidates_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Candidates:show" }
    methods:  GET

candidates_new:
    path:     /new
    defaults: { _controller: "AppBundle:Candidates:new" }
    methods:  [GET, POST]

candidates_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Candidates:edit" }
    methods:  [GET, POST]

candidates_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Candidates:delete" }
    methods:  DELETE
