resultballot_index:
    path:     /
    defaults: { _controller: "AppBundle:ResultBallot:index" }
    methods:  GET

resultballot_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ResultBallot:show" }
    methods:  GET

resultballot_new:
    path:     /new
    defaults: { _controller: "AppBundle:ResultBallot:new" }
    methods:  [GET, POST]

resultballot_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ResultBallot:edit" }
    methods:  [GET, POST]

resultballot_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ResultBallot:delete" }
    methods:  DELETE
