<?php

namespace OC\PlatformBundle\Repository;

/**
 * checkout_formRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class checkout_formRepository extends \Doctrine\ORM\EntityRepository
{
}
